In [2]:
# 슬라이드 #31

import numpy as np
a = np.arange(-15, 15).reshape(5, 6)**2
print(a)

[[225 196 169 144 121 100]
 [ 81  64  49  36  25  16]
 [  9   4   1   0   1   4]
 [  9  16  25  36  49  64]
 [ 81 100 121 144 169 196]]


In [4]:
#1) 각 행의 최대값은?
a.max(axis = 1)

array([225,  81,   9,  64, 196])

In [5]:
#2) 각 열의 평균은?
a.mean(axis = 0)

array([81., 76., 73., 72., 73., 76.])

In [7]:
#3) 전체 원소의 최소값과 그 위치는?

# 전체 원소의 최소값
a.min()

# 그 위치
a.argmin()

15