In [1]:
# 슬라이드 #40~45 4가지 함수 용법 익히기
import numpy as np

#####1) op.reduce()
''' op.reduce(a)는 1차원 배열의 모든 요소에 op를 적용함으로써 단일 값으로 감소시킨다. '''
''' 다차원 배열의 경우, op.reduce(a, axis)는 지정된 축을 따라 a의 요소에 op를 적용한다. 그 배열은 차원 수가 a보다 1차원 작다. axis의 기본값은 0이다. '''
a = np.array([1,2,3,4])
np.add.reduce(a)

10

In [2]:
a = np.array(['ab', 'cd', 'ef'], dtype='object')
np.add.reduce(a)

'abcdef'

In [3]:
a = np.array([1,1,0,1,])
np.logical_and.reduce(a)

False

In [4]:
np.logical_or.reduce(a)

True

In [5]:
a = np.arange(3) + np.arange(0, 40, 10).reshape(-1, 1)
np.add.reduce(a,1)

array([ 3, 33, 63, 93])

In [6]:
np.add.reduce(a)

array([60, 64, 68])

In [7]:
#####2) op.acumulate()
''' op.accumulate(a)는 a의 각 요소에서 reduce 연산의 중간 결과를 포함하는 새 배열을 만든다. '''
a = np.array([1,2,3,4])
np.add.accumulate(a)

array([ 1,  3,  6, 10])

In [8]:
a = np.array(['ab', 'cd', 'ef'], dtype='object')
np.add.accumulate(a)

array(['ab', 'abcd', 'abcdef'], dtype=object)

In [9]:
a = np.array([1,1,0])
np.logical_and.accumulate(a)

array([ True,  True, False])

In [10]:
np.logical_or.accumulate(a)

array([ True,  True,  True])

In [11]:
#####3) op.outer()
''' op.outer(a, b)은 op를 사용하여 a와 b 사이의 가능한 모든 요소 조합을 형성한다. 결과적으로 배열의 모양은 a와 b의 모양을 연결한 결과이다.(순서가 중요) '''
a = [1, 2, 3, 4]
b = [10, 100, 1000]
np.add.outer(a,b)

array([[  11,  101, 1001],
       [  12,  102, 1002],
       [  13,  103, 1003],
       [  14,  104, 1004]])

In [12]:
np.add.outer(b,a)

array([[  11,   12,   13,   14],
       [ 101,  102,  103,  104],
       [1001, 1002, 1003, 1004]])

In [13]:
#####4) op.reduceat()
''' op.reduceat(a, 인덱스)는 인덱스의 값에 의해 정의된 1차원 배열의 범위에 op를 적용한다. 결과적으로 배열의 길이는 인덱스와 동일하다. '''
''' 다차원 배열의 경우, reduceat()은 항상 마지막 축(2차원 배열의 행의 합)에 따라 적용된다. 이 값은 reduce()와 accumulate()의 기본값과 다르다. '''
a = np.array([0,10,20,30,40,50])
indices = np.array([1,4])
np.add.reduceat(a, indices)

array([60, 90])