In [1]:
# 슬라이드 #13

import numpy as np
a = np.arange(25).reshape(5, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [2]:
# 빨간색
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [3]:
# 파란색
a[1:4:2, :3:2]

array([[ 5,  7],
       [15, 17]])

In [4]:
# 노란색
a[-1]

array([20, 21, 22, 23, 24])