In [40]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import pandas as pd

iris = datasets.load_iris()
df_X = pd.DataFrame(iris.data)
df_Y = pd.DataFrame(iris.target)

df_X.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [41]:
df_Y.head()

0
0  0
1  0
2  0
3  0
4  0

In [53]:
# Gaussian Naive Bayes
gnb = GaussianNB()                             # 가우시안 나이브 베이즈 모델
fitted = gnb.fit(iris.data, iris.target)       # 학습 시작
y_pred = fitted.predict(iris.data)             # 학습 결과를 기존 데이터에 적용

fitted.predict_proba(iris.data)[[1,48,51,100]] # 특정 변수의 결과 뽑기(확률)

array([[1.00000000e+000, 1.51480769e-017, 2.34820051e-025],
       [1.00000000e+000, 2.63876217e-018, 2.79566024e-025],
       [7.27347795e-102, 9.45169639e-001, 5.48303606e-002],
       [3.23245181e-254, 6.35381031e-011, 1.00000000e+000]])

In [54]:
fitted.predict(iris.data)[[1,48,51,100]]    # 특정 변수의 결과 뽑기(범주)

array([0, 0, 1, 2])

In [55]:
# 성능 확인
from sklearn.metrics import confusion_matrix

confusion_matrix(iris.target, y_pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]])

In [57]:
# Multinomaial Navie Bayes
from sklearn.naive_bayes import MultinomialNB # Multinomial Naive Bayes 라이브러리
import numpy as np                            # 난수생성을 위한 행렬 라이브러리

X = np.random.randint(5,size=(6,100))        # 0부터 4까지 난수 생성, 변수 100개, sample size = 6
y = np.array([1,2,3,4,5,6])

In [61]:
clf = MultinomialNB()
clf.fit(X,y)

MultinomialNB()

In [62]:
print(clf.predict(X[2:3]))

[3]


In [63]:
clf2 = MultinomialNB(class_prior = [0.1,0.5,0.1,0.1,0.1,0.1])
clf2.fit(X,y)

MultinomialNB(class_prior=[0.1, 0.5, 0.1, 0.1, 0.1, 0.1])

In [64]:
clf2.predict_proba(X[2:3]) 

array([[4.00689668e-39, 1.99481484e-25, 1.00000000e+00, 1.61758576e-33,
        7.43480805e-35, 3.89143305e-26]])